### PR TITLE
fix: Fixed opening links in the browser

### PR DESCRIPTION
**Pull request by piotrski**
Ref: #21

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
ah nice elk already has `target="_blank"` for external links, that's handy 👍🏻 should just work on any OS as-is

**Comment by JonasKruckenberg** [comment]
can you go ahead and add a change file in the `.changes` folder too?

The basic format (also documented the in the readme of that folder) is as follows:

```
---
"elk": patch or minor or major
---

A description of your change
```

**Comment by piotrski** [comment]
All links have `target="_blank"`, but they do not work without this change.
image

Perhaps we should add information about `.changes` to the readme. BTW is there a reason we are not just using conventional commits like elk?

**Comment by JonasKruckenberg** [comment]
> What should be the name of the `.md` file? I see you are using `covector` is there cli fot that like for `changeset`

No CLI command for that yet, but maybe that changes in a few days 👀 you can call the file whatever you want

**Review by JonasKruckenberg — APPROVED** [review]
Thanks!

**Comment by piotrski** [comment]
@JonasKruckenberg we forgot to update the elk submodule, because the issue needed changes in both it was fixes here https://github.com/elk-zone/elk/pull/1268

**Comment by JonasKruckenberg** [comment]
let's update to at least the title-bar dragging PRs commit, can you open a PR for that?

**Pull request merged**
