### PR TITLE
fix: Enable window draging by the title bar

### LINKED ISSUE #10: macOS: Cannot drag window around
Not sure whether this is a generic Tauri issue or Elk Native specific, but I cannot drag the window around (using the title bar) on macOS.

(resizing the window by dragging borders does work, but I cannot move it)

### PR DESCRIPTION
**Pull request by piotrski**
https://github.com/elk-zone/elk/pull/1268 needs to be merged first
Resolves #10

### CODE REVIEW

**Comment by piotrski** [comment]
@JonasKruckenberg do you know why audit rust is failing?

**Comment by JonasKruckenberg** [comment]
> @JonasKruckenberg do you know why audit rust is failing?

Should be fixed now, please rebase 👍🏻

**Comment by JonasKruckenberg** [comment]
I don't really like how this box is the only area that is draggable, but I guess we need a better overall desktop layout anyway for this to change

Screenshot 2023-01-19 at 11 33 23

**Comment by piotrski** [comment]
Yes. It was just a quick fix. We need to work on desktop layout.

**Comment by JonasKruckenberg** [comment]
> Yes. It was just a quick fix. We need to work on desktop layout.

yeah I'm going to merge this for the time being, as *some dragging* is already better than *no dragging* 👍🏻

**Pull request merged**
